import { readFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { test, expect } from '@playwright/test'
import { createProject, seedCleanStorage, dismissLaunchPrompts, readStorage, waitForStorageHydration } from './helpers.js'

// Debug screenshots below use the OS temp dir rather than a hardcoded path —
// '/private/tmp' is a macOS-only location (Linux has no /private, and CI
// runners run as a non-root user that can't create it), so a hardcoded
// '/private/tmp/...' path made these screenshots fail with ENOENT on every
// Linux CI run while working by coincidence on a developer's Mac.
const debugScreenshotPath = name => join(tmpdir(), name)

test('new atlas creates all scales, edits and links places, undoes drawing, exports and reloads', async ({ page }) => {
  await seedCleanStorage(page)
  await page.goto('/')
  await dismissLaunchPrompts(page)
  await createProject(page, { title: 'Atlas Rebuild QA' })
  await page.getByRole('button', { name: 'Open Atlas', exact: true }).first().click()
  await page.getByRole('button', { name: 'Map', exact: true }).first().click()
  await expect(page.getByRole('heading', { name: 'Every story has a place.' })).toBeVisible()
  for (const scale of ['World','Region','Local','Interior']) {
    await page.getByRole('button', { name: '+ New map', exact: true }).click()
    const dialog = page.getByRole('dialog')
    await dialog.getByLabel('Map name').fill(`${scale} QA`)
    await dialog.getByRole('button', { name: scale, exact: true }).click()
    await dialog.getByRole('button', { name: 'Create map →' }).click()
    await expect(page.getByLabel('Map name', { exact: true })).toHaveValue(`${scale} QA`)
    await expect(page.locator('.atlas-paper [data-object-id]')).not.toHaveCount(0)
    if (scale !== 'Interior') await page.getByRole('button', { name: '← Atlas', exact: true }).click()
  }
  // Grid visibility does not silently quantize placed furniture.
  await expect(page.getByLabel('Snap to grid', { exact: true })).not.toBeChecked()
  await page.getByRole('button', { name: 'Symbols', exact: true }).click()
  const interiorCanvas = page.locator('.atlas-paper > svg')
  const interiorBox = await interiorCanvas.boundingBox()
  await interiorCanvas.click({ position: { x: interiorBox.width*.413, y: interiorBox.height*.527 } })
  let furniture = (await readStorage(page, 'nf_maps')).find(m => m.mapType === 'interior').mapObjects.at(-1)
  expect(furniture.x).toBeCloseTo(1200*.413, 0)
  expect(furniture.y).toBeCloseTo(800*.527, 0)
  await page.getByLabel('Snap to grid', { exact: true }).check()
  await interiorCanvas.click({ position: { x: interiorBox.width*.413, y: interiorBox.height*.527 } })
  furniture = (await readStorage(page, 'nf_maps')).find(m => m.mapType === 'interior').mapObjects.at(-1)
  expect(furniture.x).toBe(480)
  expect(furniture.y).toBe(440)
  await page.getByLabel('Snap to grid', { exact: true }).uncheck()
  // A placed pin links to a new Location and is editable independently.
  await page.getByRole('button', { name: 'Place', exact: true }).click()
  const canvas = page.locator('.atlas-paper svg').first()
  const box = await canvas.boundingBox()
  await canvas.click({ position: { x: box.width*.45, y: box.height*.62 } })
  await page.getByLabel('Element name').fill('Secret chamber')
  await page.getByRole('button', { name: 'Create Location from this' }).click()
  await expect(page.getByRole('button', { name: 'Open location ↗' })).toBeVisible()
  const before = await page.locator('.atlas-paper [data-object-id]').count()
  // Drag a room, then undo/redo the complete gesture.
  await page.getByRole('button', { name: 'Room', exact: true }).click()
  await page.mouse.move(box.x+box.width*.1, box.y+box.height*.6)
  await page.mouse.down()
  await page.mouse.move(box.x+box.width*.25, box.y+box.height*.8, { steps: 8 })
  await page.mouse.up()
  await expect(page.locator('.atlas-paper [data-object-id]')).toHaveCount(before+1)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.locator('.atlas-paper [data-object-id]')).toHaveCount(before)
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await expect(page.locator('.atlas-paper [data-object-id]')).toHaveCount(before+1)
  await page.locator('.atlas-export summary').click()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'PNG image', exact: true }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('Interior QA.png')
  expect(await download.failure()).toBeNull()
  await page.evaluate(() => window.__yowStorageBridge?.flush())
  await page.reload()
  await waitForStorageHydration(page)
  await expect(page.getByLabel('Map name', { exact: true })).toHaveValue('Interior QA')
  const maps = await readStorage(page, 'nf_maps')
  expect(maps).toHaveLength(4)
  const interior = maps.find(m => m.mapType === 'interior')
  const place = interior.mapObjects.find(o => o.properties?.name === 'Secret chamber')
  const locations = await readStorage(page, 'nf_locations')
  expect(place.linkedEntity.entityId).toBe(locations.find(l => l.name === 'Secret chamber').id)
  await page.setViewportSize({ width: 1024, height: 768 })
  await expect(page.getByRole('button', { name: 'Fit', exact: true })).toBeVisible()
  const fit = await page.getByRole('button', { name: 'Fit', exact: true }).boundingBox()
  expect(fit.y+fit.height).toBeLessThan(715)
  await page.screenshot({ path: debugScreenshotPath('yow-atlas-editor.png'), fullPage: true })
  await page.locator('.atlas-export summary').click()
  const jsonDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Editable map JSON' }).click()
  const exported = await jsonDownload
  const json = await readFile(await exported.path(), 'utf8')
  expect(JSON.parse(json).mapObjects.find(o => o.properties?.name === 'Secret chamber').linkedEntity).toEqual(place.linkedEntity)
  await page.getByRole('button', { name: '← Atlas', exact: true }).click()
  await page.locator('.atlas > input[type=file]').setInputFiles({ name: 'round-trip.json', mimeType: 'application/json', buffer: Buffer.from(json) })
  await expect(page.getByLabel('Map name', { exact: true })).toHaveValue('Interior QA')
  const afterImport = await readStorage(page, 'nf_maps')
  expect(afterImport).toHaveLength(5)
  expect(afterImport.at(-1).mapObjects.find(o => o.properties?.name === 'Secret chamber').linkedEntity).toEqual(place.linkedEntity)
  expect(afterImport.find(m => m.id === interior.id)).toEqual(interior)
  await page.getByRole('button', { name: '← Atlas', exact: true }).click()
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('button', { name: /World QA/ }).click()
  await page.screenshot({ path: debugScreenshotPath('yow-atlas-world.png'), fullPage: true })
})

test('existing maps retain their original editor and data when a new blank map is created', async ({ page }) => {
  await seedCleanStorage(page)
  await page.goto('/')
  await dismissLaunchPrompts(page)
  await createProject(page, { title: 'Original map safety QA' })
  const novels = await readStorage(page, 'nf_novels')
  const legacy = { id: 'legacy-map', novelId: novels[0].id, name: 'Original coast', mapType: 'world', mapObjects: [{ id: 'old-label', type: 'label', x: 400, y: 400, properties: { name: 'Preserve this', fontSize: 24 } }], metadata: { stylePreset: 'parchment' }, mapLayers: [] }
  await page.evaluate(async map => {
    window.__yowStorageBridge.setItem('nf_maps', JSON.stringify([map]))
    await window.__yowStorageBridge.flush()
  }, legacy)
  await page.reload()
  await waitForStorageHydration(page)
  await page.getByRole('navigation', { name: 'Workspace', exact: true }).getByRole('button', { name: 'Open Atlas', exact: true }).click()
  await page.getByRole('button', { name: 'Map', exact: true }).click()
  await expect(page.getByText('This map uses the original editor.')).toBeVisible()
  await page.getByRole('button', { name: 'Try the new builder' }).click()
  await page.getByRole('dialog').getByLabel('Map name').fill('A fresh start')
  await page.getByRole('button', { name: /Blank canvas/ }).click()
  await page.getByRole('button', { name: 'Create map →' }).click()
  await expect(page.locator('.atlas-paper [data-object-id]')).toHaveCount(0)
  expect((await readStorage(page, 'nf_maps')).find(m => m.id === legacy.id)).toEqual(legacy)
  await page.getByRole('button', { name: 'Land', exact: true }).click()
  const canvas = page.locator('.atlas-paper svg').first()
  const box = await canvas.boundingBox()
  await page.mouse.move(box.x+box.width*.3, box.y+box.height*.3)
  await page.mouse.down()
  for (const [x,y] of [[.6,.3],[.7,.5],[.55,.7],[.3,.6],[.3,.3]]) await page.mouse.move(box.x+box.width*x,box.y+box.height*y,{ steps: 6 })
  await page.mouse.up()
  await expect(page.locator('.atlas-paper [data-object-id]')).toHaveCount(1)
  await page.getByRole('button', { name: 'Select', exact: true }).click()
  await canvas.click({ position: { x: box.width*.5,y: box.height*.5 } })
  await expect(page.getByLabel('Element name')).toBeVisible()
  await canvas.focus()
  await page.keyboard.press('Delete')
  await expect(page.locator('.atlas-paper [data-object-id]')).toHaveCount(0)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.locator('.atlas-paper [data-object-id]')).toHaveCount(1)
})

test('cursor placement stays aligned through zoom, pan and expanded view; borders toggle without changing geometry', async ({ page }) => {
  await seedCleanStorage(page)
  await page.goto('/')
  await dismissLaunchPrompts(page)
  await createProject(page, { title: 'Pointer alignment QA' })
  await page.getByRole('navigation', { name: 'Workspace', exact: true }).getByRole('button', { name: 'Open Atlas', exact: true }).click()
  await page.getByRole('button', { name: 'Map', exact: true }).click()
  await page.getByRole('button', { name: '+ New map', exact: true }).click()
  await page.getByRole('dialog').getByLabel('Map name').fill('Alignment')
  await page.getByRole('button', { name: 'Create map →' }).click()
  const header = await page.locator('.atlas-topbar').boundingBox()
  expect(header.height).toBeLessThanOrEqual(46)
  const canvas = page.locator('.atlas-paper > svg')
  const originalPaper = await canvas.boundingBox()
  const border = page.locator('.atlas-paper [data-object-id]').first().locator('path').first()
  const organicPath = await border.getAttribute('d')
  const original = (await readStorage(page, 'nf_maps'))[0].mapObjects
  await page.getByLabel('Organic borders', { exact: true }).uncheck()
  expect(await border.getAttribute('d')).not.toContain('Q')
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  expect(await border.getAttribute('d')).toBe(organicPath)
  await page.getByLabel('Organic borders', { exact: true }).uncheck()
  expect((await readStorage(page, 'nf_maps'))[0].mapObjects).toEqual(original)
  await page.getByRole('button', { name: 'Expand canvas', exact: true }).click()
  await page.getByRole('button', { name: 'Hide panel', exact: true }).click()
  const expandedPaper = await canvas.boundingBox()
  expect(expandedPaper.width*expandedPaper.height).toBeGreaterThan(originalPaper.width*originalPaper.height*1.2)

  for (const zoom of [1, 1.25]) {
    await page.locator('.atlas-editor').evaluate((el,z) => { el.style.zoom=z }, zoom)
    await page.getByRole('button', { name: 'Zoom in', exact: true }).click()
    await page.getByRole('button', { name: 'Move view', exact: true }).click()
    await page.mouse.move(500,350)
    await page.mouse.down()
    await page.mouse.move(530,370)
    await page.mouse.up()
    await page.getByRole('button', { name: 'Place', exact: true }).click()
    const box = await canvas.boundingBox()
    const x = Math.max(150, box.x+box.width*.48), y = Math.max(200,box.y+box.height*.48)
    await page.mouse.click(x,y)
    const pin = page.locator('.atlas-paper [data-object-id]').last().locator('[data-location-dot]')
    const placed = await pin.boundingBox()
    expect(Math.abs(placed.x+placed.width/2-x)).toBeLessThan(2)
    expect(Math.abs(placed.y+placed.height/2-y)).toBeLessThan(2)
    // A closed inspector must not reopen and move the paper under the pointer.
    await expect(page.getByRole('button', { name: 'Show panel', exact: true })).toBeVisible()
  }
  await page.locator('.atlas-editor').evaluate(el => { el.style.zoom=1 })
  await page.getByRole('button', { name: 'Fit', exact: true }).click()
  await page.screenshot({ path: debugScreenshotPath('yow-atlas-expanded.png'), fullPage: true })
  await page.getByRole('button', { name: 'Exit expanded view', exact: true }).click()
  await page.evaluate(() => window.__yowStorageBridge.flush())
  await page.reload()
  await waitForStorageHydration(page)
  await expect(page.getByLabel('Organic borders', { exact: true })).not.toBeChecked()
})

test('freehand organic edges, line widths, expanded symbols and keyboard commands persist', async ({ page }) => {
  await seedCleanStorage(page)
  await page.goto('/')
  await dismissLaunchPrompts(page)
  await createProject(page, { title: 'Drawing controls QA' })
  await page.getByRole('navigation', { name: 'Workspace', exact: true }).getByRole('button', { name: 'Open Atlas', exact: true }).click()
  await page.getByRole('button', { name: 'Map', exact: true }).click()
  await page.getByRole('button', { name: '+ New map', exact: true }).click()
  await page.getByRole('dialog').getByLabel('Map name').fill('Drawing controls')
  await page.getByRole('button', { name: /Blank canvas/ }).click()
  await page.getByRole('button', { name: 'Create map →' }).click()
  const canvas = page.locator('.atlas-paper > svg')
  await page.keyboard.press('l')
  await expect(page.getByRole('button', { name: 'Land', exact: true })).toHaveAttribute('aria-pressed','true')
  const box = await canvas.boundingBox()
  await page.mouse.move(box.x+box.width*.25,box.y+box.height*.25)
  await page.mouse.down()
  for (const [x,y] of [[.65,.25],[.65,.65],[.25,.65],[.25,.25]]) await page.mouse.move(box.x+box.width*x,box.y+box.height*y,{ steps: 35 })
  await page.mouse.up()
  const shape = page.locator('.atlas-paper [data-object-id]').first()
  const rough = await shape.locator('path').first().getAttribute('d')
  const data = (await readStorage(page,'nf_maps'))[0].mapObjects[0]
  await page.getByLabel('Organic borders', { exact:true }).uncheck()
  const straight = await shape.locator('path').first().getAttribute('d')
  expect(straight).not.toBe(rough)
  await page.getByLabel('Organic borders', { exact:true }).check()
  expect(await shape.locator('path').first().getAttribute('d')).toBe(rough)
  expect((await readStorage(page,'nf_maps'))[0].mapObjects[0]).toEqual(data)
  await page.getByLabel('Border variation').fill('24')
  expect(await shape.locator('path').first().getAttribute('d')).not.toBe(rough)
  await canvas.focus()
  await page.keyboard.press('r')
  await page.getByLabel('New line thickness').fill('18')
  await page.mouse.move(box.x+box.width*.3,box.y+box.height*.35)
  await page.mouse.down()
  await page.mouse.move(box.x+box.width*.55,box.y+box.height*.55,{ steps: 15 })
  await page.mouse.up()
  await expect(page.getByLabel('Line thickness', { exact:true })).toHaveValue('18')
  await page.getByLabel('Line thickness', { exact:true }).fill('28')
  const river = page.locator('.atlas-paper [data-object-id]').last()
  await expect(river.locator('path[stroke-width="28"]')).toHaveCount(1)
  await canvas.focus()
  await page.keyboard.press('Control+z')
  await expect(page.getByRole('button', { name:'Redo', exact:true })).toBeEnabled()
  await page.keyboard.press('Control+Shift+z')
  await page.keyboard.press('p')
  await page.getByLabel('New line thickness').fill('12')
  await page.mouse.move(box.x+box.width*.3,box.y+box.height*.55)
  await page.mouse.down()
  await page.mouse.move(box.x+box.width*.6,box.y+box.height*.4,{ steps: 15 })
  await page.mouse.up()
  await page.getByLabel('Line thickness', { exact:true }).fill('22')
  await canvas.focus()
  await page.keyboard.press('s')
  await page.getByLabel('Find a symbol').fill('bridge')
  await page.getByRole('button', { name:'Bridge', exact:true }).click()
  await canvas.click({ position:{ x:box.width*.5,y:box.height*.45 } })
  await page.keyboard.press('v')
  await page.getByLabel('Element name').fill('Bridge r p v')
  // Tool keys typed into an input must remain text.
  await expect(page.getByRole('button', { name:'Select', exact:true })).toHaveAttribute('aria-pressed','true')
  await canvas.focus()
  const before = (await readStorage(page,'nf_maps'))[0].mapObjects.at(-1)
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('Shift+ArrowDown')
  const moved = (await readStorage(page,'nf_maps'))[0].mapObjects.at(-1)
  expect(moved.x).toBeCloseTo(before.x+1)
  expect(moved.y).toBeCloseTo(before.y+10)
  await page.keyboard.press('Control+d')
  await expect(page.locator('.atlas-paper [data-object-id]')).toHaveCount(5)
  await page.keyboard.press('Delete')
  await expect(page.locator('.atlas-paper [data-object-id]')).toHaveCount(4)
  await page.keyboard.press('?')
  await expect(page.getByRole('dialog', { name:'Keyboard shortcuts' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.keyboard.press('f')
  await expect(page.getByRole('button', { name:'Exit expanded view' })).toBeVisible()
  await page.keyboard.press('f')
  await page.locator('.atlas-export summary').click()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name:'SVG image' }).click()
  const svg = await readFile(await (await downloadPromise).path(),'utf8')
  expect(svg).toContain('stroke-width="28"')
  expect(svg).toContain('stroke-width="22"')
  await page.evaluate(() => window.__yowStorageBridge.flush())
  await page.reload()
  await waitForStorageHydration(page)
  const saved = (await readStorage(page,'nf_maps'))[0]
  expect(saved.metadata.organicStrength).toBe(24)
  expect(saved.mapObjects.find(o => o.type==='river').properties.size).toBe(28)
  expect(saved.mapObjects.find(o => o.type==='road').properties.size).toBe(22)
  expect(saved.mapObjects.find(o => o.properties.symbol==='bridge')).toBeTruthy()
})

test('walls use clicked vertices; dots and separate labels link by name; symbol previews resize and never export', async ({ page }) => {
  await seedCleanStorage(page)
  await page.goto('/')
  await dismissLaunchPrompts(page)
  await createProject(page, { title:'Interior drawing QA' })
  await page.getByRole('navigation', { name:'Workspace', exact:true }).getByRole('button', { name:'Open Atlas', exact:true }).click()
  await page.getByRole('button', { name:'Map', exact:true }).click()
  await page.getByRole('button', { name:'+ New map', exact:true }).click()
  await page.getByRole('dialog').getByLabel('Map name').fill('The keep')
  await page.getByRole('dialog').getByRole('button', { name:'Interior', exact:true }).click()
  await page.getByRole('button', { name:/Blank canvas/ }).click()
  await page.getByRole('button', { name:'Create map →' }).click()
  const canvas = page.locator('.atlas-paper > svg')
  const box = await canvas.boundingBox()
  await page.keyboard.press('x')
  await canvas.click({ position:{ x:box.width*.25,y:box.height*.25 } })
  await page.mouse.move(box.x+box.width*.5,box.y+box.height*.25,{ steps:20 })
  expect((await readStorage(page,'nf_maps'))[0].mapObjects).toHaveLength(0)
  await canvas.click({ position:{ x:box.width*.5,y:box.height*.25 } })
  await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5,{ steps:20 })
  await canvas.click({ position:{ x:box.width*.5,y:box.height*.5 } })
  await page.keyboard.press('Enter')
  let saved = (await readStorage(page,'nf_maps'))[0]
  expect(saved.mapObjects).toHaveLength(1)
  expect(saved.mapObjects[0].type).toBe('wall')
  expect(saved.mapObjects[0].geometry.points).toHaveLength(3)
  await page.keyboard.press('Control+z')
  expect((await readStorage(page,'nf_maps'))[0].mapObjects).toHaveLength(0)
  await page.keyboard.press('Control+Shift+z')
  await page.keyboard.press('m')
  await canvas.click({ position:{ x:box.width*.35,y:box.height*.35 } })
  await page.getByLabel('Element name').fill('Library')
  await page.getByRole('button', { name:'Create Location from this' }).click()
  await expect(page.locator('.atlas-paper [data-location-dot]')).toHaveCount(1)
  await expect(page.getByLabel('Show location label')).not.toBeChecked()
  await canvas.focus()
  await page.keyboard.press('m')
  await canvas.click({ position:{ x:box.width*.65,y:box.height*.65 } })
  await page.getByRole('combobox', { name:'Linked location', exact:true }).selectOption({ label:'Library' })
  await expect(page.getByLabel('Element name')).toHaveValue('Library')
  await page.getByLabel('Show location label').check()
  await expect(page.locator('.atlas-paper text').filter({ hasText:/^Library$/ })).toHaveCount(1)
  await canvas.focus()
  await page.keyboard.press('t')
  await canvas.click({ position:{ x:box.width*.7,y:box.height*.4 } })
  await page.getByRole('combobox', { name:'Linked location', exact:true }).selectOption({ label:'Library' })
  await expect(page.locator('.atlas-paper text').filter({ hasText:/^Library$/ })).toHaveCount(2)
  await canvas.focus()
  await page.keyboard.press('s')
  await page.getByLabel('Find a symbol').fill('bed')
  await page.getByRole('button', { name:'Bed', exact:true }).click()
  await page.getByLabel('Symbol size', { exact:true }).fill('90')
  await page.mouse.move(box.x+box.width*.7,box.y+box.height*.7)
  const preview = page.locator('.atlas-paper [data-preview]')
  await expect(preview.locator('[data-symbol="bed"]')).toHaveCount(1)
  await expect(preview.locator('g[transform="scale(1.8)"]')).toHaveCount(1)
  expect((await readStorage(page,'nf_maps'))[0].mapObjects).toHaveLength(4)
  await canvas.click({ position:{ x:box.width*.7,y:box.height*.7 } })
  saved = (await readStorage(page,'nf_maps'))[0]
  expect(saved.mapObjects.at(-1).properties).toMatchObject({ symbol:'bed',size:90 })
  await page.keyboard.press('x')
  await canvas.click({ position:{ x:box.width*.8,y:box.height*.2 } })
  await page.mouse.move(box.x+box.width*.8,box.y+box.height*.4)
  await page.locator('.atlas-export summary').click()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name:'SVG image' }).click()
  const svg = await readFile(await (await downloadPromise).path(),'utf8')
  expect(svg).not.toContain('data-preview')
  expect(svg).not.toContain('data-draft')
  expect(svg).toContain('data-symbol="bed"')
  await page.keyboard.press('Escape')
  expect((await readStorage(page,'nf_maps'))[0].mapObjects).toHaveLength(5)
  await page.evaluate(() => window.__yowStorageBridge.flush())
  await page.reload()
  await waitForStorageHydration(page)
  saved = (await readStorage(page,'nf_maps'))[0]
  expect(saved.mapObjects.filter(o => o.type === 'location')).toHaveLength(2)
  expect(saved.mapObjects.find(o => o.type === 'label').properties.name).toBe('Library')
  expect(saved.mapObjects[0].geometry.points).toHaveLength(3)
  await page.screenshot({ path:'/private/tmp/yow-atlas-interior-drawing.png', fullPage:true })
})
