// SRD-based spell compendium for the Character Builder.
// Mechanical names/levels/schools/class access follow the 5e SRD (OGL); descriptions are original short paraphrases.

export const SPELLS = [
  // ─── Cantrips (Level 0) ─────────────────────────────────────────────────
  { name: 'Acid Splash', level: 0, school: 'Conjuration', classes: ['sorcerer', 'wizard'], desc: 'Hurl a bubble of acid that splashes one or two nearby creatures for acid damage.' },
  { name: 'Blade Ward', level: 0, school: 'Abjuration', classes: ['bard', 'sorcerer', 'warlock', 'wizard'], desc: 'Ward yourself against physical attacks for a round, halving weapon damage taken.' },
  { name: 'Chill Touch', level: 0, school: 'Necromancy', classes: ['sorcerer', 'warlock', 'wizard'], desc: 'A ghostly skeletal hand deals necrotic damage and prevents the target from healing.' },
  { name: 'Dancing Lights', level: 0, school: 'Illusion', classes: ['bard', 'sorcerer', 'wizard'], desc: 'Create up to four torch-sized lights you can move around the battlefield.' },
  { name: 'Druidcraft', level: 0, school: 'Transmutation', classes: ['druid'], desc: 'A minor nature trick: predict weather, sprout a seedling, or create a small sensory effect.' },
  { name: 'Eldritch Blast', level: 0, school: 'Evocation', classes: ['warlock'], desc: 'A beam of crackling force strikes a target, the Warlock signature attack cantrip.' },
  { name: 'Fire Bolt', level: 0, school: 'Evocation', classes: ['sorcerer', 'wizard'], desc: 'Hurl a mote of fire that deals fire damage, one of the most reliable ranged cantrips.' },
  { name: 'Guidance', level: 0, school: 'Divination', classes: ['cleric', 'druid'], desc: 'Touch a creature to add a d4 to one ability check of their choice.' },
  { name: 'Light', level: 0, school: 'Evocation', classes: ['bard', 'cleric', 'sorcerer', 'wizard'], desc: 'Make an object glow like a torch for an hour.' },
  { name: 'Mage Hand', level: 0, school: 'Conjuration', classes: ['bard', 'sorcerer', 'warlock', 'wizard'], desc: 'Conjure a spectral hand to manipulate small objects at range.' },
  { name: 'Mending', level: 0, school: 'Transmutation', classes: ['bard', 'cleric', 'druid', 'sorcerer', 'wizard'], desc: 'Repair a single break or tear in an object with a touch.' },
  { name: 'Message', level: 0, school: 'Transmutation', classes: ['bard', 'sorcerer', 'wizard'], desc: 'Whisper a short message and hear a reply to a target you can see.' },
  { name: 'Minor Illusion', level: 0, school: 'Illusion', classes: ['bard', 'sorcerer', 'warlock', 'wizard'], desc: 'Create a small sound or image illusion in a nearby space.' },
  { name: 'Poison Spray', level: 0, school: 'Conjuration', classes: ['druid', 'sorcerer', 'wizard'], desc: 'Project a puff of noxious gas that deals poison damage.' },
  { name: 'Prestidigitation', level: 0, school: 'Transmutation', classes: ['bard', 'sorcerer', 'warlock', 'wizard'], desc: 'A minor magical trick: light a candle, clean an object, chill or warm food.' },
  { name: 'Produce Flame', level: 0, school: 'Conjuration', classes: ['druid'], desc: 'Conjure a flickering flame in your hand that lights the area or can be hurled.' },
  { name: 'Ray of Frost', level: 0, school: 'Evocation', classes: ['sorcerer', 'wizard'], desc: 'A ray of freezing cold deals damage and slows the target briefly.' },
  { name: 'Sacred Flame', level: 0, school: 'Evocation', classes: ['cleric'], desc: 'Flame-like radiance descends on a target that fails a Dexterity save.' },
  { name: 'Shillelagh', level: 0, school: 'Transmutation', classes: ['druid'], desc: 'Imbue a club or quarterstaff with power, using your spellcasting ability to attack.' },
  { name: 'Shocking Grasp', level: 0, school: 'Evocation', classes: ['sorcerer', 'wizard'], desc: 'Lightning springs from your hand on a melee touch, ignoring resistance from armor.' },
  { name: 'Spare the Dying', level: 0, school: 'Necromancy', classes: ['cleric'], desc: 'Stabilize a creature at 0 hit points with a touch.' },
  { name: 'Thaumaturgy', level: 0, school: 'Divination', classes: ['cleric'], desc: 'Create one of several minor supernatural flourishes to manifest divine power.' },
  { name: 'True Strike', level: 0, school: 'Divination', classes: ['bard', 'sorcerer', 'warlock', 'wizard'], desc: 'Glimpse a target’s defenses, gaining advantage on your next attack against them.' },
  { name: 'Vicious Mockery', level: 0, school: 'Enchantment', classes: ['bard'], desc: 'A string of insults laced with magic deals psychic damage and can rattle the target.' },

  // ─── Level 1 ─────────────────────────────────────────────────────────────
  { name: 'Alarm', level: 1, school: 'Abjuration', classes: ['ranger', 'wizard'], ritual: true, desc: 'Set a magical alarm that alerts you when a creature enters the warded area.' },
  { name: 'Animal Friendship', level: 1, school: 'Enchantment', classes: ['bard', 'druid', 'ranger'], desc: 'Convince a beast that you mean it no harm, keeping it calm and non-hostile.' },
  { name: 'Bane', level: 1, school: 'Enchantment', classes: ['bard', 'cleric'], concentration: true, desc: 'Up to three foes subtract a d4 from their attack rolls and saves.' },
  { name: 'Bless', level: 1, school: 'Enchantment', classes: ['cleric', 'paladin'], concentration: true, desc: 'Up to three allies add a d4 to attack rolls and saving throws.' },
  { name: 'Burning Hands', level: 1, school: 'Evocation', classes: ['sorcerer', 'wizard'], desc: 'A cone of roaring flame sweeps out from your hands.' },
  { name: 'Charm Person', level: 1, school: 'Enchantment', classes: ['bard', 'druid', 'sorcerer', 'warlock', 'wizard'], desc: 'A humanoid regards you as a friendly acquaintance if it fails a Wisdom save.' },
  { name: 'Command', level: 1, school: 'Enchantment', classes: ['cleric', 'paladin'], desc: 'Speak a one-word command, such as Drop or Flee, that a creature must obey.' },
  { name: 'Comprehend Languages', level: 1, school: 'Divination', classes: ['bard', 'sorcerer', 'warlock', 'wizard'], ritual: true, desc: 'Understand any spoken or written language for the duration.' },
  { name: 'Cure Wounds', level: 1, school: 'Evocation', classes: ['bard', 'cleric', 'druid', 'paladin', 'ranger'], desc: 'A touch restores a modest number of hit points.' },
  { name: 'Detect Evil and Good', level: 1, school: 'Divination', classes: ['cleric', 'paladin'], concentration: true, desc: 'Sense the presence of celestials, fiends, undead, or hallowed/desecrated ground.' },
  { name: 'Detect Magic', level: 1, school: 'Divination', classes: ['bard', 'cleric', 'druid', 'paladin', 'ranger', 'sorcerer', 'wizard'], ritual: true, concentration: true, desc: 'Sense the presence and school of magic within 30 feet.' },
  { name: 'Disguise Self', level: 1, school: 'Illusion', classes: ['bard', 'sorcerer', 'wizard'], desc: 'Change your appearance, including clothing and gear, for the duration.' },
  { name: 'Entangle', level: 1, school: 'Conjuration', classes: ['druid', 'ranger'], concentration: true, desc: 'Grasping weeds and vines sprout to restrain creatures in a wide area.' },
  { name: 'Faerie Fire', level: 1, school: 'Evocation', classes: ['druid'], concentration: true, desc: 'Objects and creatures in an area are outlined in light, losing the benefit of invisibility.' },
  { name: 'False Life', level: 1, school: 'Necromancy', classes: ['sorcerer', 'wizard'], desc: 'Bolster yourself with a surge of false life, gaining temporary hit points.' },
  { name: 'Feather Fall', level: 1, school: 'Transmutation', classes: ['bard', 'sorcerer', 'wizard'], desc: 'Slow the descent of up to five falling creatures to a gentle drift.' },
  { name: 'Find Familiar', level: 1, school: 'Conjuration', classes: ['wizard'], ritual: true, desc: 'Summon a small spirit in animal form to serve as a familiar and scout.' },
  { name: 'Fog Cloud', level: 1, school: 'Conjuration', classes: ['druid', 'ranger', 'sorcerer', 'wizard'], concentration: true, desc: 'Fill an area with fog that heavily obscures it.' },
  { name: 'Goodberry', level: 1, school: 'Transmutation', classes: ['druid', 'ranger'], desc: 'Conjure ten berries that each heal a little and provide a day’s food.' },
  { name: 'Grease', level: 1, school: 'Conjuration', classes: ['wizard'], desc: 'Coat the ground in slick grease, causing creatures to fall prone.' },
  { name: 'Guiding Bolt', level: 1, school: 'Evocation', classes: ['cleric'], desc: 'A flash of light streaks to a target, dealing damage and lighting them up for the next attack.' },
  { name: 'Healing Word', level: 1, school: 'Evocation', classes: ['bard', 'cleric', 'druid'], desc: 'A bonus-action word of power heals a creature at range.' },
  { name: 'Heroism', level: 1, school: 'Enchantment', classes: ['bard', 'paladin'], concentration: true, desc: 'Fill a willing creature with bravery, granting temporary hit points and immunity to fear.' },
  { name: 'Hex', level: 1, school: 'Enchantment', classes: ['warlock'], concentration: true, desc: 'Curse a target to take extra necrotic damage and suffer disadvantage on one ability.' },
  { name: "Hunter's Mark", level: 1, school: 'Divination', classes: ['ranger'], concentration: true, desc: 'Mark a quarry to deal extra damage to it and track it magically.' },
  { name: 'Identify', level: 1, school: 'Divination', classes: ['bard', 'wizard'], ritual: true, desc: 'Learn the properties of a magic item or the workings of a spell affecting a creature.' },
  { name: 'Inflict Wounds', level: 1, school: 'Necromancy', classes: ['cleric'], desc: 'A melee spell attack channels negative energy into a target.' },
  { name: 'Jump', level: 1, school: 'Transmutation', classes: ['druid', 'ranger', 'sorcerer', 'wizard'], desc: 'Triple a creature’s jump distance for the duration.' },
  { name: 'Longstrider', level: 1, school: 'Transmutation', classes: ['bard', 'druid', 'ranger', 'wizard'], desc: 'Increase a creature’s walking speed by 10 feet.' },
  { name: 'Mage Armor', level: 1, school: 'Abjuration', classes: ['sorcerer', 'wizard'], desc: 'A protective magical field sets an unarmored target’s AC to 13 + Dex.' },
  { name: 'Magic Missile', level: 1, school: 'Evocation', classes: ['sorcerer', 'wizard'], desc: 'Three darts of magical force strike unerringly, splittable among targets.' },
  { name: 'Protection from Evil and Good', level: 1, school: 'Abjuration', classes: ['cleric', 'paladin', 'warlock', 'wizard'], concentration: true, desc: 'Ward a creature against aberrations, celestials, elementals, fey, fiends, and undead.' },
  { name: 'Purify Food and Drink', level: 1, school: 'Transmutation', classes: ['cleric', 'druid'], ritual: true, desc: 'Remove poison and spoilage from food and drink in a small area.' },
  { name: 'Sanctuary', level: 1, school: 'Abjuration', classes: ['cleric'], desc: 'Ward a creature so attackers must make a Wisdom save or choose a new target.' },
  { name: 'Shield', level: 1, school: 'Abjuration', classes: ['sorcerer', 'wizard'], desc: 'An instant reactive barrier grants +5 AC and blocks Magic Missile entirely.' },
  { name: 'Shield of Faith', level: 1, school: 'Abjuration', classes: ['cleric', 'paladin'], concentration: true, desc: 'A shimmering field grants an ally +2 AC for the duration.' },
  { name: 'Silent Image', level: 1, school: 'Illusion', classes: ['bard', 'sorcerer', 'wizard'], concentration: true, desc: 'Create a purely visual illusion of an object, creature, or phenomenon.' },
  { name: 'Sleep', level: 1, school: 'Enchantment', classes: ['bard', 'sorcerer', 'wizard'], concentration: true, desc: 'Magical slumber falls over creatures in an area, weakest hit points first.' },
  { name: 'Speak with Animals', level: 1, school: 'Divination', classes: ['bard', 'druid', 'ranger'], ritual: true, desc: 'Comprehend and verbally communicate with beasts for the duration.' },
  { name: 'Thunderwave', level: 1, school: 'Evocation', classes: ['bard', 'druid', 'sorcerer', 'wizard'], desc: 'A wave of thunderous force pushes nearby creatures back and deals damage.' },
  { name: 'Witch Bolt', level: 1, school: 'Evocation', classes: ['sorcerer', 'warlock', 'wizard'], concentration: true, desc: 'A beam of lightning forms a sustained arc that can be renewed each turn.' },

  // ─── Level 2 ─────────────────────────────────────────────────────────────
  { name: 'Aid', level: 2, school: 'Abjuration', classes: ['cleric', 'paladin'], desc: 'Bolster up to three allies’ hit point maximum and current hit points.' },
  { name: 'Alter Self', level: 2, school: 'Transmutation', classes: ['sorcerer', 'wizard'], concentration: true, desc: 'Reshape your body: grow a swimmer’s form, natural weapons, or a disguise.' },
  { name: 'Animal Messenger', level: 2, school: 'Enchantment', classes: ['bard', 'druid', 'ranger'], ritual: true, desc: 'Send a small animal to deliver a short message to a designated location.' },
  { name: 'Barkskin', level: 2, school: 'Transmutation', classes: ['druid', 'ranger'], concentration: true, desc: 'A creature’s skin toughens, setting its AC to at least 16.' },
  { name: 'Blindness/Deafness', level: 2, school: 'Necromancy', classes: ['bard', 'cleric', 'sorcerer', 'wizard'], desc: 'Blind or deafen a target unless it succeeds on a Constitution save.' },
  { name: 'Blur', level: 2, school: 'Illusion', classes: ['sorcerer', 'wizard'], concentration: true, desc: 'Your outline blurs, giving attackers disadvantage on their attacks against you.' },
  { name: 'Branding Smite', level: 2, school: 'Evocation', classes: ['paladin'], concentration: true, desc: 'Your next weapon hit sears the target with light, dealing extra damage and revealing it.' },
  { name: 'Calm Emotions', level: 2, school: 'Enchantment', classes: ['bard', 'cleric'], concentration: true, desc: 'Suppress violent emotion or charm effects in a group of creatures.' },
  { name: 'Darkness', level: 2, school: 'Evocation', classes: ['sorcerer', 'warlock', 'wizard'], concentration: true, desc: 'Magical darkness spreads from a point, blocking normal light and darkvision.' },
  { name: 'Darkvision', level: 2, school: 'Transmutation', classes: ['druid', 'ranger', 'sorcerer', 'wizard'], desc: 'Grant a creature the ability to see in the dark up to 60 feet.' },
  { name: 'Enhance Ability', level: 2, school: 'Transmutation', classes: ['bard', 'cleric', 'druid', 'sorcerer'], concentration: true, desc: 'Grant advantage on checks tied to one chosen ability score.' },
  { name: 'Enlarge/Reduce', level: 2, school: 'Transmutation', classes: ['sorcerer', 'wizard'], concentration: true, desc: 'Double or halve a creature or object’s size, affecting its Strength and damage.' },
  { name: 'Find Steed', level: 2, school: 'Conjuration', classes: ['paladin'], desc: 'Summon a loyal spirit steed to serve as a mount.' },
  { name: 'Find Traps', level: 2, school: 'Divination', classes: ['cleric', 'ranger'], desc: 'Sense the presence of any trap within range.' },
  { name: 'Flame Blade', level: 2, school: 'Evocation', classes: ['druid'], concentration: true, desc: 'Conjure a fiery blade of light for use as a melee weapon.' },
  { name: 'Flaming Sphere', level: 2, school: 'Conjuration', classes: ['druid', 'wizard'], concentration: true, desc: 'A five-foot flaming sphere rolls around the battlefield at your command.' },
  { name: 'Gentle Repose', level: 2, school: 'Necromancy', classes: ['cleric', 'wizard'], ritual: true, desc: 'Protect a corpse from decay and from becoming undead.' },
  { name: 'Gust of Wind', level: 2, school: 'Evocation', classes: ['druid', 'sorcerer', 'wizard'], concentration: true, desc: 'A line of strong wind pushes creatures back and disperses gas and fog.' },
  { name: 'Heat Metal', level: 2, school: 'Transmutation', classes: ['druid'], concentration: true, desc: 'Cause a metal object to glow red hot, searing whoever holds or wears it.' },
  { name: 'Hold Person', level: 2, school: 'Enchantment', classes: ['bard', 'cleric', 'druid', 'sorcerer', 'warlock', 'wizard'], concentration: true, desc: 'Paralyze a humanoid target that fails a Wisdom saving throw.' },
  { name: 'Invisibility', level: 2, school: 'Illusion', classes: ['bard', 'sorcerer', 'warlock', 'wizard'], concentration: true, desc: 'A creature you touch becomes invisible until it attacks or casts a spell.' },
  { name: 'Lesser Restoration', level: 2, school: 'Abjuration', classes: ['bard', 'cleric', 'druid', 'paladin', 'ranger'], desc: 'End one disease or condition afflicting a touched creature.' },
  { name: 'Levitate', level: 2, school: 'Transmutation', classes: ['sorcerer', 'wizard'], concentration: true, desc: 'Make a creature or object float upward and hover in place.' },
  { name: 'Locate Animals or Plants', level: 2, school: 'Divination', classes: ['druid', 'ranger'], ritual: true, desc: 'Learn the location of the nearest creature or plant of a specific kind.' },
  { name: 'Locate Object', level: 2, school: 'Divination', classes: ['bard', 'cleric', 'druid', 'paladin', 'ranger', 'wizard'], concentration: true, desc: 'Sense the direction to a familiar object or object type within range.' },
  { name: 'Mirror Image', level: 2, school: 'Illusion', classes: ['sorcerer', 'warlock', 'wizard'], desc: 'Three illusory duplicates of yourself confuse incoming attacks.' },
  { name: 'Misty Step', level: 2, school: 'Conjuration', classes: ['sorcerer', 'warlock', 'wizard'], desc: 'Teleport in a puff of silver mist up to 30 feet as a bonus action.' },
  { name: 'Moonbeam', level: 2, school: 'Evocation', classes: ['druid'], concentration: true, desc: 'A pale beam of light sears creatures that stand within it each turn.' },
  { name: 'Pass without Trace', level: 2, school: 'Abjuration', classes: ['druid', 'ranger'], concentration: true, desc: 'Cloak a group in shadow, granting a large bonus to Stealth and hiding their tracks.' },
  { name: 'Prayer of Healing', level: 2, school: 'Evocation', classes: ['cleric'], desc: 'Restore hit points to up to six creatures over a ten-minute ritual.' },
  { name: 'Protection from Poison', level: 2, school: 'Abjuration', classes: ['cleric', 'druid', 'paladin', 'ranger'], desc: 'Neutralize a poison and grant resistance to poison damage for an hour.' },
  { name: 'Ray of Enfeeblement', level: 2, school: 'Necromancy', classes: ['warlock', 'wizard'], concentration: true, desc: 'A black ray weakens a target, halving the damage of its Strength attacks.' },
  { name: 'Scorching Ray', level: 2, school: 'Evocation', classes: ['sorcerer', 'wizard'], desc: 'Hurl three separate rays of fire that can be aimed at one or more targets.' },
  { name: 'See Invisibility', level: 2, school: 'Divination', classes: ['bard', 'sorcerer', 'wizard'], desc: 'See invisible creatures and objects, and see into the Ethereal Plane.' },
  { name: 'Silence', level: 2, school: 'Illusion', classes: ['bard', 'cleric', 'ranger'], ritual: true, concentration: true, desc: 'Suppress all sound within an area, blocking spells with verbal components.' },
  { name: 'Spider Climb', level: 2, school: 'Transmutation', classes: ['sorcerer', 'warlock', 'wizard'], concentration: true, desc: 'A creature gains the ability to move up, down, and across vertical surfaces.' },
  { name: 'Spike Growth', level: 2, school: 'Transmutation', classes: ['druid', 'ranger'], concentration: true, desc: 'The ground in an area sprouts hazardous spikes, slowing and damaging movement through it.' },
  { name: 'Spiritual Weapon', level: 2, school: 'Evocation', classes: ['cleric'], desc: 'Conjure a floating spectral weapon that attacks as a bonus action.' },
  { name: 'Suggestion', level: 2, school: 'Enchantment', classes: ['bard', 'sorcerer', 'warlock', 'wizard'], concentration: true, desc: 'Plant a reasonable-sounding suggestion that a creature is compelled to follow.' },
  { name: 'Warding Bond', level: 2, school: 'Abjuration', classes: ['cleric'], desc: 'Link two creatures so one shares damage and resistances with the other.' },
  { name: 'Web', level: 2, school: 'Conjuration', classes: ['sorcerer', 'wizard'], concentration: true, desc: 'Thick sticky webbing fills an area, restraining creatures caught inside.' },
  { name: 'Zone of Truth', level: 2, school: 'Enchantment', classes: ['bard', 'cleric', 'paladin'], desc: 'Creatures in an area cannot speak a deliberate lie while inside it.' },

  // ─── Level 3 ─────────────────────────────────────────────────────────────
  { name: 'Animate Dead', level: 3, school: 'Necromancy', classes: ['cleric', 'wizard'], desc: 'Raise a skeleton or zombie from a corpse to fight under your command.' },
  { name: 'Aura of Vitality', level: 3, school: 'Abjuration', classes: ['paladin'], concentration: true, desc: 'An aura of healing energy lets you heal a nearby creature each turn as a bonus action.' },
  { name: 'Beacon of Hope', level: 3, school: 'Abjuration', classes: ['cleric'], concentration: true, desc: 'Grant advantage on Wisdom saves and death saves, and maximize healing received.' },
  { name: 'Bestow Curse', level: 3, school: 'Necromancy', classes: ['bard', 'cleric', 'wizard'], concentration: true, desc: 'Curse a creature with one of several debilitating magical afflictions.' },
  { name: 'Blink', level: 3, school: 'Transmutation', classes: ['sorcerer', 'warlock', 'wizard'], desc: 'Randomly flicker between the Material Plane and the Ethereal Plane each turn.' },
  { name: 'Call Lightning', level: 3, school: 'Conjuration', classes: ['druid'], concentration: true, desc: 'Summon a storm cloud that you can call down bolts of lightning from each turn.' },
  { name: 'Clairvoyance', level: 3, school: 'Divination', classes: ['bard', 'cleric', 'sorcerer', 'wizard'], concentration: true, desc: 'Create an invisible sensor to see or hear at a distant location.' },
  { name: 'Conjure Animals', level: 3, school: 'Conjuration', classes: ['druid', 'ranger'], concentration: true, desc: 'Summon spirits that take the form of beasts to fight alongside you.' },
  { name: 'Counterspell', level: 3, school: 'Abjuration', classes: ['sorcerer', 'warlock', 'wizard'], desc: 'Interrupt a creature in the process of casting a spell, potentially negating it entirely.' },
  { name: 'Create Food and Water', level: 3, school: 'Conjuration', classes: ['cleric', 'paladin'], desc: 'Conjure enough food and water to sustain a group for a day.' },
  { name: 'Daylight', level: 3, school: 'Evocation', classes: ['cleric', 'druid', 'paladin', 'ranger', 'sorcerer'], desc: 'A 60-foot radius of bright sunlight erupts from a point, dispelling magical darkness.' },
  { name: 'Dispel Magic', level: 3, school: 'Abjuration', classes: ['bard', 'cleric', 'druid', 'paladin', 'sorcerer', 'warlock', 'wizard'], desc: 'End one ongoing magical effect on a creature, object, or area.' },
  { name: 'Elemental Weapon', level: 3, school: 'Transmutation', classes: ['paladin'], concentration: true, desc: 'Imbue a weapon with an elemental energy, granting a bonus to hit and extra damage.' },
  { name: 'Fear', level: 3, school: 'Illusion', classes: ['bard', 'sorcerer', 'warlock', 'wizard'], concentration: true, desc: 'Project a phantasmal image of horror, causing creatures to drop items and flee.' },
  { name: 'Feign Death', level: 3, school: 'Necromancy', classes: ['bard', 'cleric', 'druid', 'wizard'], ritual: true, desc: 'Place a willing creature into a cataleptic state indistinguishable from death.' },
  { name: 'Fireball', level: 3, school: 'Evocation', classes: ['sorcerer', 'wizard'], desc: 'A bright streak blossoms into a roaring explosion of fire, the classic area blaster.' },
  { name: 'Fly', level: 3, school: 'Transmutation', classes: ['sorcerer', 'warlock', 'wizard'], concentration: true, desc: 'Grant a creature a flying speed for the duration.' },
  { name: 'Gaseous Form', level: 3, school: 'Transmutation', classes: ['sorcerer', 'warlock', 'wizard'], concentration: true, desc: 'Transform a willing creature into a misty cloud able to squeeze through tiny gaps.' },
  { name: 'Glyph of Warding', level: 3, school: 'Abjuration', classes: ['bard', 'cleric', 'wizard'], desc: 'Inscribe a glyph that triggers a spell or explosion when its trigger condition is met.' },
  { name: 'Haste', level: 3, school: 'Transmutation', classes: ['sorcerer', 'wizard'], concentration: true, desc: 'Double a creature’s speed and grant an extra action, minus a bonus attack.' },
  { name: 'Hunger of Hadar', level: 3, school: 'Conjuration', classes: ['warlock'], concentration: true, desc: 'Tear open a rift to a void that damages and blinds creatures trapped within it.' },
  { name: 'Hypnotic Pattern', level: 3, school: 'Illusion', classes: ['bard', 'sorcerer', 'warlock', 'wizard'], concentration: true, desc: 'A twisting pattern of colors charms creatures into a mesmerized stupor.' },
  { name: 'Lightning Bolt', level: 3, school: 'Evocation', classes: ['sorcerer', 'wizard'], desc: 'A stroke of lightning blasts a line, damaging everything caught in its path.' },
  { name: 'Magic Circle', level: 3, school: 'Abjuration', classes: ['cleric', 'paladin', 'warlock', 'wizard'], desc: 'Draw a ward that traps or repels a chosen category of extraplanar creatures.' },
  { name: 'Major Image', level: 3, school: 'Illusion', classes: ['bard', 'sorcerer', 'warlock', 'wizard'], concentration: true, desc: 'Create a lasting illusion complete with sound, smell, and temperature.' },
  { name: 'Mass Healing Word', level: 3, school: 'Evocation', classes: ['cleric'], desc: 'A bonus-action word heals up to six creatures at a distance.' },
  { name: 'Meld into Stone', level: 3, school: 'Transmutation', classes: ['cleric', 'druid'], ritual: true, desc: 'Merge your body and gear into a stone surface, hiding within it.' },
  { name: 'Nondetection', level: 3, school: 'Abjuration', classes: ['bard', 'ranger', 'wizard'], desc: 'Hide a target from divination magic and scrying sensors.' },
  { name: 'Plant Growth', level: 3, school: 'Transmutation', classes: ['druid', 'ranger'], desc: 'Overgrow an area with lush vegetation or enrich the land for a season.' },
  { name: 'Protection from Energy', level: 3, school: 'Abjuration', classes: ['cleric', 'druid', 'ranger', 'sorcerer', 'wizard'], concentration: true, desc: 'Grant resistance to one damage type of your choice.' },
  { name: 'Remove Curse', level: 3, school: 'Abjuration', classes: ['cleric', 'paladin', 'warlock', 'wizard'], desc: 'Lift all curses affecting a creature or object, including cursed magic items.' },
  { name: 'Revivify', level: 3, school: 'Necromancy', classes: ['cleric', 'paladin'], desc: 'Return a creature dead no longer than a minute back to life with 1 hit point.' },
  { name: 'Sending', level: 3, school: 'Evocation', classes: ['bard', 'cleric', 'wizard'], desc: 'Send a short telepathic message to a known creature anywhere and get a short reply.' },
  { name: 'Sleet Storm', level: 3, school: 'Conjuration', classes: ['sorcerer', 'wizard'], concentration: true, desc: 'Freezing rain and sleet coats an area, causing creatures to slip and fall prone.' },
  { name: 'Speak with Dead', level: 3, school: 'Necromancy', classes: ['bard', 'cleric'], desc: 'Question a corpse, which answers with whatever knowledge it had in life.' },
  { name: 'Speak with Plants', level: 3, school: 'Transmutation', classes: ['bard', 'druid', 'ranger'], desc: 'Imbue plants with limited sentience so they answer questions and can be commanded.' },
  { name: 'Spirit Guardians', level: 3, school: 'Conjuration', classes: ['cleric'], concentration: true, desc: 'Spectral guardians orbit you, damaging and slowing enemies that come close.' },
  { name: 'Stinking Cloud', level: 3, school: 'Conjuration', classes: ['sorcerer', 'wizard'], concentration: true, desc: 'A cloud of nauseating gas can leave creatures retching and unable to act.' },
  { name: 'Tongues', level: 3, school: 'Divination', classes: ['bard', 'cleric', 'sorcerer', 'warlock', 'wizard'], desc: 'Understand and be understood by any creature that speaks a language.' },
  { name: 'Vampiric Touch', level: 3, school: 'Necromancy', classes: ['sorcerer', 'warlock', 'wizard'], concentration: true, desc: 'A melee touch drains life from a target, healing you for half the damage dealt.' },
  { name: 'Wind Wall', level: 3, school: 'Evocation', classes: ['druid', 'ranger'], concentration: true, desc: 'A wall of wind deflects small projectiles and disperses gas and vapor.' },

  // ─── Level 4 ─────────────────────────────────────────────────────────────
  { name: 'Arcane Eye', level: 4, school: 'Divination', classes: ['wizard'], concentration: true, desc: 'Create an invisible floating eye you can move around and see through.' },
  { name: 'Aura of Life', level: 4, school: 'Abjuration', classes: ['paladin'], concentration: true, desc: 'An aura grants resistance to necrotic damage and prevents maximum HP reduction.' },
  { name: 'Aura of Purity', level: 4, school: 'Abjuration', classes: ['paladin'], concentration: true, desc: 'An aura wards nearby allies against disease, poison, and being charmed or frightened.' },
  { name: 'Banishment', level: 4, school: 'Abjuration', classes: ['cleric', 'sorcerer', 'warlock', 'wizard'], concentration: true, desc: 'Send a creature to a harmless demiplane, removing it from the fight if it fails a save.' },
  { name: 'Blight', level: 4, school: 'Necromancy', classes: ['druid', 'sorcerer', 'warlock', 'wizard'], desc: 'Draw the moisture and life from a target, dealing heavy necrotic damage.' },
  { name: 'Compulsion', level: 4, school: 'Enchantment', classes: ['bard'], concentration: true, desc: 'Force a creature to move in a direction of your choosing each of its turns.' },
  { name: 'Confusion', level: 4, school: 'Enchantment', classes: ['bard', 'druid', 'sorcerer', 'wizard'], concentration: true, desc: 'Creatures in an area act randomly, wandering or attacking whoever is nearest.' },
  { name: 'Conjure Minor Elementals', level: 4, school: 'Conjuration', classes: ['druid', 'wizard'], concentration: true, desc: 'Summon a group of lesser elemental creatures to fight for you.' },
  { name: 'Conjure Woodland Beings', level: 4, school: 'Conjuration', classes: ['druid', 'ranger'], concentration: true, desc: 'Summon fey creatures of the forest to answer your call.' },
  { name: 'Control Water', level: 4, school: 'Transmutation', classes: ['cleric', 'druid', 'wizard'], concentration: true, desc: 'Manipulate a body of water: part it, flood it, redirect it, or whirlpool it.' },
  { name: 'Death Ward', level: 4, school: 'Abjuration', classes: ['cleric', 'paladin'], desc: 'The next time a warded creature would drop to 0 hit points, it stays at 1 instead.' },
  { name: 'Dimension Door', level: 4, school: 'Conjuration', classes: ['bard', 'sorcerer', 'warlock', 'wizard'], desc: 'Teleport yourself, and possibly a companion, up to 500 feet in an instant.' },
  { name: 'Dominate Beast', level: 4, school: 'Enchantment', classes: ['druid', 'sorcerer'], concentration: true, desc: 'Seize control of a beast’s mind and issue it commands telepathically.' },
  { name: 'Fabricate', level: 4, school: 'Transmutation', classes: ['wizard'], desc: 'Convert raw materials into a finished product of the same material.' },
  { name: 'Fire Shield', level: 4, school: 'Evocation', classes: ['sorcerer', 'wizard'], desc: 'Wreathe yourself in flame or frost, resisting one energy type and burning attackers.' },
  { name: 'Freedom of Movement', level: 4, school: 'Abjuration', classes: ['bard', 'cleric', 'druid', 'ranger'], desc: 'A creature moves and acts unhindered by difficult terrain, restraint, or paralysis.' },
  { name: 'Grasping Vine', level: 4, school: 'Conjuration', classes: ['druid', 'ranger'], concentration: true, desc: 'A vine whips out each turn to grapple and drag a creature toward you.' },
  { name: 'Greater Invisibility', level: 4, school: 'Illusion', classes: ['bard', 'sorcerer', 'wizard'], concentration: true, desc: 'A creature turns invisible even while attacking or casting spells.' },
  { name: 'Guardian of Faith', level: 4, school: 'Conjuration', classes: ['cleric'], desc: 'A large spectral guardian patrols an area, striking anyone hostile who enters it.' },
  { name: 'Hallucinatory Terrain', level: 4, school: 'Illusion', classes: ['bard', 'druid', 'sorcerer', 'wizard'], desc: 'Make a natural terrain feature look, sound, and smell like a different one.' },
  { name: 'Ice Storm', level: 4, school: 'Evocation', classes: ['druid', 'sorcerer', 'wizard'], desc: 'Hail and ice hammer a cylindrical area, dealing bludgeoning and cold damage.' },
  { name: 'Locate Creature', level: 4, school: 'Divination', classes: ['bard', 'cleric', 'druid', 'paladin', 'ranger', 'sorcerer', 'wizard'], concentration: true, desc: 'Sense the direction toward a known creature or type of creature.' },
  { name: "Mordenkainen's Faithful Hound", level: 4, school: 'Conjuration', classes: ['wizard'], desc: 'Conjure an invisible watchdog that barks at intruders and can bite them.' },
  { name: "Otiluke's Resilient Sphere", level: 4, school: 'Evocation', classes: ['wizard'], concentration: true, desc: 'Encase a creature or object in an impenetrable sphere of shimmering force.' },
  { name: 'Phantasmal Killer', level: 4, school: 'Illusion', classes: ['sorcerer', 'wizard'], concentration: true, desc: 'Conjure a target’s deepest fear as an illusion that can frighten it to death.' },
  { name: 'Polymorph', level: 4, school: 'Transmutation', classes: ['bard', 'druid', 'sorcerer', 'wizard'], concentration: true, desc: 'Transform a creature, willing or not, into a beast of comparable challenge.' },
  { name: 'Stone Shape', level: 4, school: 'Transmutation', classes: ['cleric', 'druid', 'wizard'], desc: 'Reshape a section of stone into any form useful to you.' },
  { name: 'Stoneskin', level: 4, school: 'Abjuration', classes: ['druid', 'ranger', 'sorcerer', 'wizard'], concentration: true, desc: 'A creature’s skin hardens, granting resistance to nonmagical bludgeoning, piercing, and slashing.' },
  { name: 'Wall of Fire', level: 4, school: 'Evocation', classes: ['druid', 'sorcerer', 'wizard'], concentration: true, desc: 'Conjure a wall of roaring flame that burns anything passing through it.' },

  // ─── Level 5 ─────────────────────────────────────────────────────────────
  { name: 'Animate Objects', level: 5, school: 'Transmutation', classes: ['bard', 'sorcerer', 'wizard'], concentration: true, desc: 'Bring up to ten small objects to life to fight on your behalf.' },
  { name: 'Antilife Shell', level: 5, school: 'Abjuration', classes: ['druid'], concentration: true, desc: 'A shimmering barrier prevents most living creatures from passing through it.' },
  { name: 'Awaken', level: 5, school: 'Transmutation', classes: ['bard', 'druid'], desc: 'Grant a beast or plant human-like intelligence and the ability to speak.' },
  { name: 'Circle of Power', level: 5, school: 'Abjuration', classes: ['paladin'], concentration: true, desc: 'Allies in a radius around you gain advantage on saves against spells and magical effects.' },
  { name: 'Cloudkill', level: 5, school: 'Conjuration', classes: ['sorcerer', 'wizard'], concentration: true, desc: 'A sphere of poisonous yellow-green fog rolls across the battlefield, killing the weak.' },
  { name: 'Commune', level: 5, school: 'Divination', classes: ['cleric'], ritual: true, desc: 'Ask your deity up to three yes-or-no questions about the immediate future.' },
  { name: 'Commune with Nature', level: 5, school: 'Divination', classes: ['druid', 'ranger'], ritual: true, desc: 'Become one with nature to learn facts about the surrounding terrain.' },
  { name: 'Cone of Cold', level: 5, school: 'Evocation', classes: ['sorcerer', 'wizard'], desc: 'A blast of frigid air erupts from your hands in a wide cone.' },
  { name: 'Conjure Elemental', level: 5, school: 'Conjuration', classes: ['druid', 'wizard'], concentration: true, desc: 'Summon an elemental spirit from one of the four elemental planes.' },
  { name: 'Contact Other Plane', level: 5, school: 'Divination', classes: ['warlock', 'wizard'], ritual: true, desc: 'Send your mind to an extraplanar entity to ask it up to five questions.' },
  { name: 'Contagion', level: 5, school: 'Necromancy', classes: ['cleric', 'druid'], desc: 'Infect a target with a magical disease that worsens the longer it goes untreated.' },
  { name: 'Creation', level: 5, school: 'Illusion', classes: ['sorcerer', 'wizard'], desc: 'Shape shadowstuff into a real, nonliving object of vegetable or mineral matter.' },
  { name: 'Dispel Evil and Good', level: 5, school: 'Abjuration', classes: ['cleric', 'paladin'], concentration: true, desc: 'Protect yourself against celestials, elementals, fey, fiends, and undead, and can banish them.' },
  { name: 'Dominate Person', level: 5, school: 'Enchantment', classes: ['bard', 'sorcerer', 'wizard'], concentration: true, desc: 'Seize total control of a humanoid’s mind, issuing commands as you please.' },
  { name: 'Dream', level: 5, school: 'Illusion', classes: ['bard', 'warlock', 'wizard'], desc: 'Send a message or nightmare into a sleeping creature’s dreams.' },
  { name: 'Flame Strike', level: 5, school: 'Evocation', classes: ['cleric'], desc: 'A column of divine fire roars down from above onto a target area.' },
  { name: 'Geas', level: 5, school: 'Enchantment', classes: ['bard', 'cleric', 'druid', 'paladin', 'wizard'], desc: 'Place a magical command on a creature that harms it if it disobeys.' },
  { name: 'Greater Restoration', level: 5, school: 'Abjuration', classes: ['bard', 'cleric', 'druid'], desc: 'Undo a powerful curse, restore a drained ability score, or remove exhaustion.' },
  { name: 'Hallow', level: 5, school: 'Evocation', classes: ['cleric'], desc: 'Consecrate a site, warding out extraplanar creatures and adding a chosen magical effect.' },
  { name: 'Hold Monster', level: 5, school: 'Enchantment', classes: ['bard', 'sorcerer', 'warlock', 'wizard'], concentration: true, desc: 'Paralyze any creature, not just humanoids, that fails a Wisdom save.' },
  { name: 'Insect Plague', level: 5, school: 'Conjuration', classes: ['cleric', 'druid', 'sorcerer'], concentration: true, desc: 'A cloud of biting, stinging locusts fills an area and damages anyone inside.' },
  { name: 'Legend Lore', level: 5, school: 'Divination', classes: ['bard', 'cleric', 'wizard'], desc: 'Learn important lore about a named person, place, or object.' },
  { name: 'Mass Cure Wounds', level: 5, school: 'Evocation', classes: ['bard', 'cleric', 'druid'], desc: 'A wave of healing energy restores hit points to up to six creatures at once.' },
  { name: 'Modify Memory', level: 5, school: 'Enchantment', classes: ['bard', 'wizard'], concentration: true, desc: 'Reshape a creature’s memory of an event from the past 24 hours.' },
  { name: 'Passwall', level: 5, school: 'Transmutation', classes: ['wizard'], desc: 'Create a temporary passage through wood, plaster, or stone.' },
  { name: 'Planar Binding', level: 5, school: 'Abjuration', classes: ['bard', 'cleric', 'druid', 'wizard'], desc: 'Bind a celestial, elemental, fey, or fiend to your service for a length of time.' },
  { name: 'Raise Dead', level: 5, school: 'Necromancy', classes: ['bard', 'cleric', 'paladin'], desc: 'Return a creature dead no more than ten days to life with its old body intact.' },
  { name: 'Reincarnate', level: 5, school: 'Transmutation', classes: ['druid'], desc: 'Bring a dead creature back to life in a new, randomly determined body.' },
  { name: 'Scrying', level: 5, school: 'Divination', classes: ['bard', 'cleric', 'druid', 'warlock', 'wizard'], concentration: true, desc: 'Create an invisible sensor to see and hear a specific creature anywhere.' },
  { name: 'Telekinesis', level: 5, school: 'Transmutation', classes: ['sorcerer', 'wizard'], concentration: true, desc: 'Move or manipulate objects and creatures with your mind at a distance.' },
  { name: 'Teleportation Circle', level: 5, school: 'Conjuration', classes: ['bard', 'sorcerer', 'wizard'], desc: 'Draw a circle that opens a portal to a permanent teleportation circle you know.' },
  { name: 'Tree Stride', level: 5, school: 'Conjuration', classes: ['druid', 'ranger'], concentration: true, desc: 'Step into a tree and out another tree of the same species within range.' },
  { name: 'Wall of Force', level: 5, school: 'Evocation', classes: ['wizard'], concentration: true, desc: 'An invisible wall of pure force blocks physical and magical passage alike.' },
  { name: 'Wall of Stone', level: 5, school: 'Evocation', classes: ['druid', 'sorcerer', 'wizard'], concentration: true, desc: 'Conjure a nonmagical wall of solid stone in a shape of your choosing.' },

  // ─── Level 6 ─────────────────────────────────────────────────────────────
  { name: 'Arcane Gate', level: 6, school: 'Conjuration', classes: ['sorcerer', 'wizard'], concentration: true, desc: 'Create two linked portals that let creatures step instantly between them.' },
  { name: 'Blade Barrier', level: 6, school: 'Evocation', classes: ['cleric'], concentration: true, desc: 'A wall of whirling blades damages and blocks any creature that tries to pass.' },
  { name: 'Chain Lightning', level: 6, school: 'Evocation', classes: ['sorcerer', 'wizard'], desc: 'A bolt of lightning arcs from target to target, striking up to four creatures.' },
  { name: 'Circle of Death', level: 6, school: 'Necromancy', classes: ['sorcerer', 'warlock', 'wizard'], desc: 'A sphere of negative energy washes over an area, withering everything within it.' },
  { name: 'Conjure Fey', level: 6, school: 'Conjuration', classes: ['druid', 'warlock'], concentration: true, desc: 'Summon a fey creature or beast native to the Feywild to fight for you.' },
  { name: 'Contingency', level: 6, school: 'Evocation', classes: ['wizard'], desc: 'Prepare a spell to trigger automatically when a chosen condition occurs.' },
  { name: 'Create Undead', level: 6, school: 'Necromancy', classes: ['cleric', 'warlock', 'wizard'], desc: 'Animate ghouls or more powerful undead from corpses to serve you.' },
  { name: 'Disintegrate', level: 6, school: 'Transmutation', classes: ['sorcerer', 'wizard'], desc: 'A thin green ray reduces a target to dust if the damage is severe enough.' },
  { name: "Drawmij's Instant Summons", level: 6, school: 'Conjuration', classes: ['wizard'], ritual: true, desc: 'Enchant an item so that speaking a word teleports it into your hand.' },
  { name: 'Eyebite', level: 6, school: 'Necromancy', classes: ['bard', 'sorcerer', 'warlock', 'wizard'], concentration: true, desc: 'Your gaze can frighten, panic into sleep, or sicken a creature each turn.' },
  { name: 'Find the Path', level: 6, school: 'Divination', classes: ['bard', 'cleric', 'druid'], concentration: true, desc: 'Discover the shortest, most direct route to a known location.' },
  { name: 'Forbiddance', level: 6, school: 'Abjuration', classes: ['cleric'], ritual: true, desc: 'Ward an area against teleportation and against a chosen creature type entering.' },
  { name: 'Globe of Invulnerability', level: 6, school: 'Abjuration', classes: ['sorcerer', 'wizard'], concentration: true, desc: 'An immobile sphere blocks spells of 5th level or lower from entering.' },
  { name: 'Guards and Wards', level: 6, school: 'Abjuration', classes: ['bard', 'wizard'], desc: 'A network of magical effects protects up to 2,500 square feet of floor space.' },
  { name: 'Harm', level: 6, school: 'Necromancy', classes: ['cleric'], desc: 'Devastating negative energy deals massive damage and reduces a target’s hit point maximum.' },
  { name: 'Heal', level: 6, school: 'Evocation', classes: ['cleric', 'druid'], desc: 'A surge of positive energy restores a large number of hit points and ends blindness or disease.' },
  { name: "Heroes' Feast", level: 6, school: 'Conjuration', classes: ['cleric', 'druid'], desc: 'Conjure a magnificent feast that cures illness, grants resistance to fear, and more.' },
  { name: 'Mass Suggestion', level: 6, school: 'Enchantment', classes: ['bard', 'sorcerer', 'warlock', 'wizard'], desc: 'Plant a compelling suggestion in the minds of up to twelve creatures at once.' },
  { name: 'Move Earth', level: 6, school: 'Transmutation', classes: ['druid', 'sorcerer', 'wizard'], concentration: true, desc: 'Reshape dirt, sand, or clay over a large area, digging trenches or raising hills.' },
  { name: "Otiluke's Freezing Sphere", level: 6, school: 'Evocation', classes: ['sorcerer', 'wizard'], desc: 'Hurl a frigid globe that explodes into a blast of cold, or freezes water solid.' },
  { name: "Otto's Irresistible Dance", level: 6, school: 'Enchantment', classes: ['bard', 'sorcerer', 'warlock', 'wizard'], desc: 'Force a creature into an uncontrollable comic dance that leaves it vulnerable.' },
  { name: 'Planar Ally', level: 6, school: 'Conjuration', classes: ['cleric'], desc: 'Beseech a powerful celestial, elemental, or fiend to lend aid, for a price.' },
  { name: 'Programmed Illusion', level: 6, school: 'Illusion', classes: ['bard', 'wizard'], desc: 'Create an illusion that activates when a specific trigger condition occurs.' },
  { name: 'Sunbeam', level: 6, school: 'Evocation', classes: ['druid', 'sorcerer', 'wizard'], concentration: true, desc: 'A beam of brilliant light blinds and burns creatures each turn it is sustained.' },
  { name: 'True Seeing', level: 6, school: 'Divination', classes: ['bard', 'cleric', 'sorcerer', 'warlock', 'wizard'], desc: 'Grant a creature truesight, seeing through illusions and into the Ethereal Plane.' },
  { name: 'Wall of Ice', level: 6, school: 'Evocation', classes: ['sorcerer', 'wizard'], concentration: true, desc: 'Conjure a wall of ice, or an ice dome, that can trap and damage creatures.' },
  { name: 'Wind Walk', level: 6, school: 'Transmutation', classes: ['druid', 'ranger'], desc: 'Turn yourself and allies into gaseous form with a fast flying speed.' },
  { name: 'Word of Recall', level: 6, school: 'Conjuration', classes: ['cleric'], desc: 'Instantly teleport yourself and allies back to a previously designated sanctuary.' },

  // ─── Level 7 ─────────────────────────────────────────────────────────────
  { name: 'Conjure Celestial', level: 7, school: 'Conjuration', classes: ['cleric'], concentration: true, desc: 'Summon a celestial spirit that fights for you and can heal your allies.' },
  { name: 'Delayed Blast Fireball', level: 7, school: 'Evocation', classes: ['sorcerer', 'wizard'], concentration: true, desc: 'A fireball that grows more devastating for every round its detonation is delayed.' },
  { name: 'Divine Word', level: 7, school: 'Evocation', classes: ['cleric'], desc: 'Utter a word of pure divine power that can banish, deafen, blind, or kill weaker foes.' },
  { name: 'Etherealness', level: 7, school: 'Transmutation', classes: ['bard', 'cleric', 'sorcerer', 'warlock', 'wizard'], desc: 'Step partway into the Ethereal Plane, seeing and moving through solid objects.' },
  { name: 'Finger of Death', level: 7, school: 'Necromancy', classes: ['sorcerer', 'warlock', 'wizard'], desc: 'Send negative energy coursing through a creature, which can rise as a zombie if slain.' },
  { name: 'Fire Storm', level: 7, school: 'Evocation', classes: ['cleric', 'druid'], desc: 'Roaring flames erupt across an area of your choice, scorching everything within it.' },
  { name: 'Forcecage', level: 7, school: 'Evocation', classes: ['bard', 'warlock', 'wizard'], desc: 'Conjure an invisible cage or box of solid force to imprison creatures.' },
  { name: 'Mirage Arcane', level: 7, school: 'Illusion', classes: ['bard', 'druid', 'wizard'], desc: 'Make a terrain feature covering a huge area look, sound, and feel completely different.' },
  { name: "Mordenkainen's Magnificent Mansion", level: 7, school: 'Conjuration', classes: ['bard', 'wizard'], desc: 'Conjure an extradimensional dwelling complete with servants for a day.' },
  { name: "Mordenkainen's Sword", level: 7, school: 'Evocation', classes: ['bard', 'wizard'], concentration: true, desc: 'Conjure a spectral sword that fights on your behalf as a bonus action.' },
  { name: 'Plane Shift', level: 7, school: 'Conjuration', classes: ['cleric', 'druid', 'sorcerer', 'warlock', 'wizard'], desc: 'Transport yourself and up to eight others to a different plane of existence.' },
  { name: 'Prismatic Spray', level: 7, school: 'Evocation', classes: ['sorcerer', 'wizard'], desc: 'Eight rays of shimmering, multicolored light each carry a different devastating effect.' },
  { name: 'Regenerate', level: 7, school: 'Transmutation', classes: ['bard', 'cleric', 'druid'], desc: 'A creature regrows lost limbs and heals rapidly for the duration.' },
  { name: 'Resurrection', level: 7, school: 'Necromancy', classes: ['bard', 'cleric'], desc: 'Return a creature dead up to a century to life, fully healed and restored.' },
  { name: 'Reverse Gravity', level: 7, school: 'Transmutation', classes: ['druid', 'sorcerer', 'wizard'], concentration: true, desc: 'Gravity reverses in an area, sending unsecured creatures and objects flying upward.' },
  { name: 'Symbol', level: 7, school: 'Abjuration', classes: ['bard', 'cleric', 'wizard'], desc: 'Inscribe a runic symbol that unleashes a powerful magical effect when triggered.' },
  { name: 'Teleport', level: 7, school: 'Conjuration', classes: ['bard', 'sorcerer', 'wizard'], desc: 'Instantly transport yourself and others to a familiar or described destination.' },

  // ─── Level 8 ─────────────────────────────────────────────────────────────
  { name: 'Animal Shapes', level: 8, school: 'Transmutation', classes: ['druid'], desc: 'Transform every willing ally nearby into a beast form of your choosing.' },
  { name: 'Antimagic Field', level: 8, school: 'Abjuration', classes: ['cleric', 'wizard'], concentration: true, desc: 'A 10-foot aura suppresses spells and magic items within it entirely.' },
  { name: 'Antipathy/Sympathy', level: 8, school: 'Enchantment', classes: ['druid', 'wizard'], desc: 'Enchant an object or location to attract or repel a chosen kind of creature.' },
  { name: 'Clone', level: 8, school: 'Necromancy', classes: ['wizard'], desc: 'Grow a duplicate body that your soul transfers into if you die.' },
  { name: 'Control Weather', level: 8, school: 'Transmutation', classes: ['cleric', 'druid', 'wizard'], concentration: true, desc: 'Change the weather in a large area over the course of several hours.' },
  { name: 'Demiplane', level: 8, school: 'Conjuration', classes: ['warlock', 'wizard'], desc: 'Create a door leading to a bare demiplane you can furnish and expand over time.' },
  { name: 'Dominate Monster', level: 8, school: 'Enchantment', classes: ['bard', 'sorcerer', 'warlock', 'wizard'], concentration: true, desc: 'Seize control of any creature’s mind, humanoid or otherwise.' },
  { name: 'Earthquake', level: 8, school: 'Evocation', classes: ['cleric', 'druid', 'sorcerer'], concentration: true, desc: 'The ground within a large radius ripples, cracks, and can swallow creatures whole.' },
  { name: 'Feeblemind', level: 8, school: 'Enchantment', classes: ['bard', 'druid', 'warlock', 'wizard'], desc: 'Blast a creature’s mind, potentially reducing its Intelligence and Charisma to 1.' },
  { name: 'Glibness', level: 8, school: 'Transmutation', classes: ['bard', 'warlock'], desc: 'Replace your Charisma checks with a flat high roll for the duration, and beat lie detection.' },
  { name: 'Holy Aura', level: 8, school: 'Abjuration', classes: ['cleric'], concentration: true, desc: 'Allies shine with holy light, gaining advantage on saves and blinding attackers.' },
  { name: 'Incendiary Cloud', level: 8, school: 'Conjuration', classes: ['sorcerer', 'wizard'], concentration: true, desc: 'A cloud of roiling smoke embedded with fire damages creatures each round.' },
  { name: 'Maze', level: 8, school: 'Conjuration', classes: ['warlock', 'wizard'], concentration: true, desc: 'Banish a creature to a labyrinthine demiplane until it escapes or the spell ends.' },
  { name: 'Mind Blank', level: 8, school: 'Abjuration', classes: ['bard', 'wizard'], desc: 'Grant a creature total immunity to divination and mind-affecting effects for a day.' },
  { name: 'Power Word Stun', level: 8, school: 'Enchantment', classes: ['bard', 'sorcerer', 'warlock', 'wizard'], desc: 'Speak a word of power that instantly stuns a creature with enough hit points left.' },
  { name: 'Sunburst', level: 8, school: 'Evocation', classes: ['druid', 'sorcerer', 'wizard'], desc: 'Brilliant sunlight fills a huge area, blinding and burning everything caught inside.' },

  // ─── Level 9 ─────────────────────────────────────────────────────────────
  { name: 'Astral Projection', level: 9, school: 'Necromancy', classes: ['cleric', 'warlock', 'wizard'], desc: 'Project yourself and companions onto the Astral Plane, leaving your bodies behind.' },
  { name: 'Foresight', level: 9, school: 'Divination', classes: ['bard', 'druid', 'warlock', 'wizard'], desc: 'A creature gains an uncanny knack for avoiding harm, granting advantage broadly for a day.' },
  { name: 'Gate', level: 9, school: 'Conjuration', classes: ['cleric', 'sorcerer', 'wizard'], concentration: true, desc: 'Open a portal to another plane, or to a specific location on your own.' },
  { name: 'Imprisonment', level: 9, school: 'Abjuration', classes: ['warlock', 'wizard'], desc: 'Bind a creature in one of several inescapable magical prisons.' },
  { name: 'Mass Heal', level: 9, school: 'Evocation', classes: ['cleric'], desc: 'A flood of healing energy restores hit points to as many creatures as you can reach.' },
  { name: 'Meteor Swarm', level: 9, school: 'Evocation', classes: ['sorcerer', 'wizard'], desc: 'Blazing orbs of fire plummet from the sky, devastating everything below.' },
  { name: 'Power Word Heal', level: 9, school: 'Evocation', classes: ['bard'], desc: 'A word of power fully heals a creature and ends many debilitating conditions.' },
  { name: 'Power Word Kill', level: 9, school: 'Enchantment', classes: ['bard', 'sorcerer', 'warlock', 'wizard'], desc: 'Speak a word of power that instantly slays a creature with enough hit points left.' },
  { name: 'Prismatic Wall', level: 9, school: 'Abjuration', classes: ['wizard'], desc: 'Seven shimmering layers of light form an impassable barrier of escalating effects.' },
  { name: 'Shapechange', level: 9, school: 'Transmutation', classes: ['druid', 'wizard'], concentration: true, desc: 'Transform into any creature you have seen, keeping your own mind and memories.' },
  { name: 'Storm of Vengeance', level: 9, school: 'Conjuration', classes: ['druid'], concentration: true, desc: 'A vast storm cloud unleashes escalating fury: hail, lightning, thunder, and gale winds.' },
  { name: 'Time Stop', level: 9, school: 'Transmutation', classes: ['sorcerer', 'wizard'], desc: 'Briefly stop time for everyone but yourself, granting a burst of free turns.' },
  { name: 'True Polymorph', level: 9, school: 'Transmutation', classes: ['bard', 'warlock', 'wizard'], concentration: true, desc: 'Transform a creature or object into another form, permanently if sustained long enough.' },
  { name: 'True Resurrection', level: 9, school: 'Necromancy', classes: ['cleric', 'druid'], desc: 'Return a creature to life even from dust, with no material component required.' },
  { name: 'Weird', level: 9, school: 'Illusion', classes: ['warlock', 'wizard'], concentration: true, desc: 'Conjure illusions of each enemy’s deepest fears, capable of frightening them to death.' },
  { name: 'Wish', level: 9, school: 'Conjuration', classes: ['sorcerer', 'wizard'], desc: 'The mightiest spell mortals can cast, capable of replicating nearly any lesser spell or altering reality.' },
]

export const spellsForClassAtLevel = (classId, maxSpellLevel) => {
  return SPELLS.filter(s => s.classes.includes(classId) && s.level >= 1 && s.level <= maxSpellLevel)
}

export const cantripsForClass = (classId) => SPELLS.filter(s => s.level === 0 && s.classes.includes(classId))

export const findSpellByName = (name) => SPELLS.find(s => s.name === name)
