// @vitest-environment jsdom
//
// Export ownership gate (2 Oct sprint day): one matrix over all six project
// types (novel, novella, short_story, dnd_campaign, ttrpg, comic) that drives
// the REAL ZIP, Word, World Bible PDF and visual HTML export paths and then
// inspects the generated bytes. Proves (a) the user's own content is present
// and readable in every format and (b) private data — manuscript prose in the
// World Bible, disabled sections, secrets that must never leave the app
// (AI keys, session tokens) — is absent where promised.
import { describe, expect, it } from 'vitest'
import { strFromU8, unzipSync } from 'fflate'
import { createProjectZipBlob } from './projectExport.js'
import { createProjectDocxBlob, createProjectDocxZipBlob } from './projectExportDocx.js'
import { createProjectPdfBlob, createProjectVisualPdfHtml } from './projectExportPdf.js'

const TYPES = ['novel', 'novella', 'short_story', 'dnd_campaign', 'ttrpg', 'comic']
const SECTIONS = ['outline', 'characters', 'locations', 'lore', 'ideas', 'timeline', 'worldhistory']

const makeData = (type) => {
  const id = `p-${type}`
  return {
    project: {
      id, title: `Matrix ${type}`, type, enabledSections: SECTIONS.filter(s => s !== 'ideas'),
      aiChatSessions: [{ id: 'chat', novelId: id, title: 'Chat', category: 'Outline', messages: [
        { role: 'user', content: `CHAT USER ${type}` }, { role: 'assistant', content: `CHAT REPLY ${type}` },
      ] }],
      // Must never appear in any export:
      aiApiKey: 'sk-SECRET-AI-KEY', supabaseSession: 'SECRET-SESSION-TOKEN',
    },
    characters: [{ id: 'c1', novelId: id, name: `Hero ${type}`, role: 'Lead', bio: `BIO ${type}` }],
    factions: [], eras: [], maps: [], whiteboards: [], storySchedule: [],
    locations: [{ id: 'l1', novelId: id, name: `Place ${type}`, description: `PLACE DESC ${type}` }],
    timeline: [{ id: 't1', novelId: id, title: `Event ${type}`, description: `EVENT DESC ${type}` }],
    worldHistory: [{ id: 'h1', novelId: id, title: `History ${type}`, content: `HISTORY BODY ${type}` }],
    acts: [{ id: 'a1', novelId: id, title: 'Act One', order: 1 }],
    chapters: [{ id: 'ch1', novelId: id, actId: 'a1', title: 'Chapter One', order: 1 }],
    scenes: [{ id: 's1', novelId: id, chapterId: 'ch1', title: 'Scene', order: 1,
      content: `MANUSCRIPT PROSE ${type}`, notes: [{ id: 'n1', title: 'Note', body: `PRIVATE NOTE ${type}` }] }],
    loreEntries: [{ id: 'lo1', novelId: id, title: `Lore ${type}`, content: `LORE BODY ${type}` }],
    ideaEntries: [{ id: 'i1', novelId: id, title: 'Idea', body: `DISABLED IDEA ${type}` }],
    ...(type === 'comic' ? { comicPages: [{ id: 'cp1', novelId: id, order: 1 }], comicPanels: [{ id: 'cpn1', pageId: 'cp1', description: 'PANEL DESC' }] } : {}),
  }
}

const latin1 = async (blob) => new TextDecoder('latin1').decode(await blob.arrayBuffer())
const docXml = async (blob) => strFromU8(unzipSync(new Uint8Array(await blob.arrayBuffer()))['word/document.xml'])
const SECRETS = ['sk-SECRET-AI-KEY', 'SECRET-SESSION-TOKEN']

describe.each(TYPES)('export ownership matrix: %s', (type) => {
  it('ZIP is a complete, restorable copy of the user content (including disabled sections)', async () => {
    const data = makeData(type)
    const files = unzipSync(new Uint8Array(await (await createProjectZipBlob(data)).arrayBuffer()))
    const payload = JSON.parse(strFromU8(files['project-data.json']))
    expect(JSON.parse(strFromU8(files['manifest.json'])).projectId).toBe(`p-${type}`)
    expect(payload.scenes[0].content).toBe(`MANUSCRIPT PROSE ${type}`)
    expect(payload.characters[0].bio).toBe(`BIO ${type}`)
    expect(payload.ideaEntries[0].body).toBe(`DISABLED IDEA ${type}`) // ZIP is the full-ownership copy
    expect(Boolean(files['data/comic-pages.json'])).toBe(type === 'comic')
  })

  it('Word export is readable, includes the AI chat, hides disabled sections and prose-free private notes', async () => {
    const data = makeData(type)
    const full = await docXml(await createProjectDocxBlob(data))
    for (const v of [`Hero ${type}`, `BIO ${type}`, `Place ${type}`, `LORE BODY ${type}`, `CHAT USER ${type}`, `CHAT REPLY ${type}`]) expect(full).toContain(v)
    expect(full).not.toContain(`DISABLED IDEA ${type}`)
    for (const s of SECRETS) expect(full).not.toContain(s)
    const zip = unzipSync(new Uint8Array(await (await createProjectDocxZipBlob(data)).arrayBuffer()))
    expect(Object.keys(zip).filter(n => n.endsWith('.docx')).length).toBeGreaterThan(0)
  })

  it('World Bible PDF and visual HTML contain world content but no prose, private notes, disabled sections or secrets', async () => {
    const data = makeData(type)
    const pdf = await latin1(await createProjectPdfBlob(data))
    const html = createProjectVisualPdfHtml(data)
    expect(pdf.startsWith('%PDF-')).toBe(true)
    for (const out of [pdf, html]) {
      expect(out).toContain(`BIO ${type}`)
      for (const bad of [`MANUSCRIPT PROSE ${type}`, `PRIVATE NOTE ${type}`, `DISABLED IDEA ${type}`, '%%YOW-DATA-BEGIN%%', ...SECRETS]) {
        expect(out).not.toContain(bad)
      }
    }
  })
})
