// @vitest-environment jsdom
//
// QA_PLAN.md Priority -1 "PDF privacy" deferred item / docs/ROADMAP.md's
// Export ownership gate: PDF export used to embed a hidden, lossless
// `%%YOW-DATA-BEGIN%% ... %%YOW-DATA-END%%` full-project-JSON payload (read
// back by AIImportModal.jsx's tryReadYowPdf() for "import a YOW PDF"), which
// meant disabling a section or writing a private note before sharing a PDF
// did not actually keep that content out of the file — the full project was
// still recoverable from the raw bytes. The Owner launch handoff (2026-09-07)
// removed that embed from the export path (tryReadYowPdf() is kept only to
// still import old files that already have it). This test is the missing
// regression coverage for that change: it proves both halves generatively
// rather than by reading the code — no embed marker ever appears in a
// generated PDF's raw bytes, and content belonging to a disabled section
// does not leak into those bytes either, exactly the two ways a "share-safe"
// PDF could still leak project data.
import { describe, expect, it } from 'vitest'
import { createProjectPdfBlob } from './projectExportPdf.js'

const ALL_SECTIONS = [
  'outline', 'characters', 'familytree', 'relationships', 'factions', 'locations', 'lore', 'ideas',
  'schedule', 'timeline', 'worldhistory', 'map',
]

const makeProjectData = (enabledSections) => ({
  project: {
    id: 'project-1',
    title: 'Stormrider',
    type: 'novel',
    enabledSections,
  },
  characters: [{ id: 'char-1', novelId: 'project-1', name: 'Mara Vale', role: 'Mentor', bio: 'SECRET CHARACTER BIO' }],
  factions: [],
  locations: [],
  timeline: [],
  worldHistory: [],
  eras: [],
  acts: [{ id: 'act-1', novelId: 'project-1', title: 'Act One', order: 1 }],
  chapters: [{ id: 'chapter-1', novelId: 'project-1', actId: 'act-1', title: 'Chapter One', order: 1 }],
  scenes: [{
    id: 'scene-1', novelId: 'project-1', chapterId: 'chapter-1', title: 'Opening', order: 1,
    content: 'SECRET MANUSCRIPT PROSE', notes: [{ id: 'note-1', title: 'Private note', body: 'SECRET PRIVATE NOTE BODY' }],
  }],
  loreEntries: [{ id: 'lore-1', novelId: 'project-1', title: 'Signal Law', content: 'SECRET LORE CONTENT' }],
  ideaEntries: [{ id: 'idea-1', novelId: 'project-1', title: 'Twist', body: 'SECRET IDEA BODY' }],
  maps: [],
  whiteboards: [],
  storySchedule: [],
})

async function pdfBytesToLatin1(blob) {
  const buffer = await blob.arrayBuffer()
  // Mirrors AIImportModal.jsx's own readPdfFile()/tryReadYowPdf() decode —
  // a lossless byte<->char mapping, so a substring search here catches
  // anything those same readers could recover.
  return new TextDecoder('latin1').decode(buffer)
}

describe('createProjectPdfBlob privacy', () => {
  it('never embeds the legacy hidden full-project-JSON payload', async () => {
    const data = makeProjectData(ALL_SECTIONS)
    const raw = await pdfBytesToLatin1(await createProjectPdfBlob(data))
    expect(raw).not.toContain('%%YOW-DATA-BEGIN%%')
    expect(raw).not.toContain('%%YOW-DATA-END%%')
    // The manuscript prose itself is not part of the World Bible PDF's
    // promised content at all (see the export scope decision in
    // docs/ROADMAP.md) — confirm it never appears, embed or otherwise.
    expect(raw).not.toContain('SECRET MANUSCRIPT PROSE')
    expect(raw).not.toContain('SECRET PRIVATE NOTE BODY')
  })

  it('keeps a disabled section entirely out of the generated bytes, not just off the visible page', async () => {
    const enabled = ALL_SECTIONS.filter(s => s !== 'lore' && s !== 'ideas')
    const data = makeProjectData(enabled)
    const raw = await pdfBytesToLatin1(await createProjectPdfBlob(data))
    expect(raw).not.toContain('SECRET LORE CONTENT')
    expect(raw).not.toContain('SECRET IDEA BODY')
    // Sanity check the test itself: an enabled section's content IS present,
    // proving the absence above is real filtering and not a broken encoder.
    expect(raw).toContain('SECRET CHARACTER BIO')
  })
})
